### ISSUE TITLE
Headless/node rendering

### ISSUE THREAD

**Issue by arvind** [uwdata/vega#10]
Vega 1 was capable of running as a headless/node.js service. Vega 2 should be capable of this as well. But, what changes are necessary with our new requirejs architecture?

**Comment by kanitw** [comment]
Using [Universal Module Pattern](https://github.com/umdjs/umd)?

**Comment by arvind** [comment]
@kanitw, thanks! I was previously using amdWeb, which explains the trouble I was having w/Node. I updated it to returnExports in bea0638, and it's working more seamlessly now. So, now we can begin to port the vg.headless package from vg1 (though we should re-evaluate whether a separate package is still needed).
