### ISSUE TITLE
"Half of band width" in a Vega expression?

### ISSUE THREAD

**Issue by waxlamp** [uwdata/vega#12]
I'm working on a bar chart, and I want to place the labels at 90 degrees, in the center of each bar.  This expression will get me the left edge of a bar:

```
{"scale": "x", field: "data.xvar"}
```

and this one will get me half the width of the bars:

```
{"scale": "x", band: true, "mult": 0.5}
```

but I don't know how to combine them.  I tried on a lark to stuff each expression into the `offset` property of the other, but that doesn't work.

What's the right way to do this?  Thanks!

**Comment by arvind** [comment]
From @jheer:

> Labels often require both "anchor" positions and subsequent offsets. That is why they have dx and dy properties.
> 
> ``` json
> "X": {"scale": "x", "field": "data.xvar"},
> "dx": {"scale": "x", "band": true, "mult": 0.5}
> ```
> 
> Et voila!
> -jeff

**Comment by waxlamp** [comment]
Thanks!  This is very useful info.

One more question.  I am trying to render bar chart labels at an angle, to display all of them without smashing them together, while not rendering them completely sideways.  It seems I can't combine the `dx` property with `angle` in the way that I want:  When I say `angle` is 45 and `dx` is, e.g., 10, what happens is, the text is first rotated, then moved through a "local" `dx` of 10.  What I really want is for the text to move to the right by 10, and _then_ rotate through the requested angle.  Is there any way to do that?

I hope this made sense :).
