### ISSUE TITLE
overview+detail example doesn't work in Safari or Firefox

### ISSUE THREAD

**Issue by marcprux** [uwdata/vega#20]
The "overview+detail.json" example works fine in Chrome, but in Safari and Firefox it only renders the axes and ticks without any marks. There are no messages in the Javascript console indicating any errors. Same result for both canvas and SVG renderer.

Inspecting the DOM with the SVG renderer shows that the "type-area" group is size 0x0 in Safari, but 720x378 in Chrome, making me suspect that Chrome's group is inheriting the parent size whereas it isn't in Safari. But it probably isn't a pure SVG issue, since it affects the Canvas renderer the same way.

Environment: latest version of all browsers on Mac 10.10 running examples in editor using `python -m SimpleHTTPServer 8000`

**Comment by arvind** [comment]
Nice catch again, Marc! Luckily, this wasn't a deeper issue but rather that Safari and Firefox need the day of month in order to parse dates correctly from the csv. Fixed in c42687c.
