### ISSUE TITLE
Porting data transforms and layouts

### ISSUE THREAD

**Issue by arvind** [uwdata/vega#3]
Vega 2 should support all the data transformations and layouts listed from Vega 1 (http://github.com/trifacta/vega/wiki/Data-Transforms)
## Data Transforms
- [x] aggregate
- [x] ~~array~~
- [x] ~~copy~~
- [x] cross
- [x] facet
- [x] filter
- [x] ~~flatten~~
- [x] fold
- [x] formula
- [x] ~~slice~~
- [x] sort
- [x] ~~stats~~
- [x] truncate
- [x] unique
- [ ] window
- [x] zip
## Visual Layouts
- [x] force
- [x] geo
- [x] geopath
- [x] link
- [x] pie
- [x] stack
- [x] treemap
- [ ] wordcloud

**Comment by RussellSprouts** [comment]
I've been looking at the sort transform -- it doesn't seem to work, because it always passes null for `d`

```
var by = expr.eval(model, fn, null, null, null, null, node._deps.signals);
```

**Comment by kanitw** [comment]
and newly added in 1.4.3?
- [x] aggregate
- [x] bin

**Comment by arvind** [comment]
@RussellSprouts good catch. Addressed this with c05f50e. Sort can now take a FieldName | SignalName | Array<FieldName|SignalName>. FieldName may be prepended by a minus sign to denote descending sort order. A signal should return a FieldName (and optional minus sign).

**Comment by RussellSprouts** [comment]
I'm working on stats right now.

**Comment by RussellSprouts** [comment]
I'm working on copy right now.

**Comment by arvind** [comment]
As we port transforms over, an important question to think about is where allowing signals makes sense. All transform properties? Some? Consistency?
