### ISSUE TITLE
Hover style should be supported as a simple shortcut

### ISSUE THREAD

**Issue by ajturner** [uwdata/vega#35]
[Since hover is tentatively removed in v2](Per https://github.com/uwdata/vega/issues/34#issuecomment-87474006) - suggesting that `hover` still be supported if the graphics developer does not need to dive into interactions.

Opening for discussion per @arvind in [this comment](https://github.com/uwdata/vega/issues/34#issuecomment-87474006)

**Comment by ajturner** [comment]
@arvind curious if this is still on your radar or not? Or suggestions for the best way to implement.

**Comment by arvind** [comment]
It's still on the radar. We're still investigating performance w/o including `hover` in the `dirtyChecking` branch, and will likely make a final decision about including the property once we merged it in. Sorry about the delay.

**Comment by arvind** [comment]
We brought back the hover property set in b09cc3f, which should now be available in the main `v2` branch. Thanks for keeping the issue on our radar, Andrew!

**Comment by ajturner** [comment]
:chart_with_upwards_trend: yay

**Comment by arvind** [comment]
Heads up, I reverted the merge as it broke our SVG renderer. It's currently in the `dirtyChecking` branch and we'll merge it back in once we fix the bug!

**Comment by ajturner** [comment]
Thanks :chart_with_downwards_trend:

**Comment by arvind** [comment]
Annnd it's back :)
