### ISSUE TITLE
Reactive geometry imposes mark ordering restrictions

### ISSUE THREAD

**Issue by marcprux** [uwdata/vega#36]
The "grouped_bar" example at https://github.com/uwdata/vega/blob/v2/examples/spec/grouped_bar.json has changed from vega v1 to make the positioning of the text marks be relative to the bar marks using a new syntax `"from": {"mark": "bars"}`, which is a great feature. It seems to have been added in #18.

However, if I re-order the marks in the example so the text mark comes first, I see an error in the JS console:

``` error
[Error] TypeError: undefined is not an object (evaluating 'child.builder')
    (anonymous function) (d3.v3.min.js, line 1)
```

It should be possible to reference other marks without imposing ordering requirements, since you may want to, say, have the dependent marks be positioned underneath the source mark.

**Comment by arvind** [comment]
Right, this is a requirement of reactive geometry. A mark must be built (data join) and encoded in order for it to serve as the backing data for another mark. The build and encode steps also insert generated mark instances into the scene graph, which determines the z-axis ordering. 

It's important to note that this doesn't reduce Vega's expressivity. If, for example, a layout _requires_ reactive geometry (i.e., is difficult/impossible to express in the Vega 1 language) but needs to break out of the imposed mark order, one could always create initial "ghost" marks that are transparent but have the necessary properties set and then derived the actual marks from them.
