### ISSUE TITLE
"e" variable in streams of signal types

### ISSUE THREAD

**Issue by RussellSprouts** [uwdata/vega#38]
If a stream has a type of a signal rather than an event, then the "e" variable should have the value of the signal. This would allow interactors to define signals that behave much like events.

**Comment by jheer** [comment]
While considering this issue, we should also consider consolidation of expression arguments (e, i, p). Issues include potential renaming, bundling into a shared object (e.g., adding item as a property of the event), and possibly removing 'p' in favor of dedicated point lookup functions.

**Comment by ajturner** [comment]
+1 for using variable names that are _human readable_

**Comment by arvind** [comment]
Addressed "human readability" in #51, but not changing the behaviour of `event` which should be a DOM event, if available. Derived signals should use signal names in the expression.
