### ISSUE TITLE
Automatic layout and truncation of labels

### ISSUE THREAD

**Issue by ajturner** [uwdata/vega#53]
Vega uses `width` and `height` to define the plot area of a chart. 

The issue is that Vega does not handle any axes label placement or tick label adjustments (angle/truncation) automatically. The result is that generating charts programatically often results in overlapping labels. 

would it be possible internal to vega to add logic for 'better defaults'. E.g. placing the label outside tick labels if they exist and angle or truncate tick labels that would overlap?

![](https://cloud.githubusercontent.com/assets/5304673/6514159/20760738-c335-11e4-8a5a-8f4522b8e8e8.png)

Default labeling overlaps on long text:

![localhost_8000_overlap_html](https://cloud.githubusercontent.com/assets/1218/7732409/e655474c-fef5-11e4-814c-7e7b16125d8c.png)

Angle labels overlaps axis label:

![localhost_8000_overlap_html](https://cloud.githubusercontent.com/assets/1218/7732402/d2f062ae-fef5-11e4-8175-5c86854b7dbf.png)

Related to https://github.com/Esri/cedar/issues/66

**Comment by kanitw** [comment]
@ajturner  We had some rule-based logic for determining axis truncation and axis title placement.  
However, it’s not perfect yet and it will be revisited while we migrate Vega-lite to use Vega 2.

**Comment by arvind** [comment]
On the Vega 2 front, we're working on addressing this issue. It should hopefully be more tractable than Vega 1 thanks to our new reactive geometry.

**Comment by arvind** [comment]
@ajturner, we've unfortunately not had a chance to address this within the Vega 2.0 release cycle. However, we're hoping to get to it for the next release. As we've just merged things over to the vega/vega repository, we want to consolidate issues/etc. Do you mind re-opening this issue there (if it doesn't already exist). Thank you!
