### ISSUE TITLE
Rectangle width, offset, and band are not behaving correctly

### ISSUE THREAD

**Issue by ajturner** [uwdata/vega#63]
I'm trying to specify the bar spacing between two types of plots - Histograms and Ordinal.
## Ordinal

> the space between bars or groups of bars roughly equal the width of a single bar

[per Stephen Few](http://sfew.websitetoolbox.com/post/show_single_post?pid=15347133&postcount=2) 

However I can't seem to achieve this. Using the [vega v2 editor](http://idl.cs.washington.edu/projects/reactive-vega/examples/editor/) choosing Bar, narrowing down to just 4 values and investigating width:
### Width: { Band:true }

``` json
"marks": {
   "properties": {
       "enter": {
          "width": {"scale": "x", "band": true, "offset": -1},
}}}
```

![vega_live_editor](https://cloud.githubusercontent.com/assets/1218/7950245/dd894274-0965-11e5-9370-c217e4d91cb7.png)

Bars centered on Ticks, but I want half-width spacing between the bars
### Width

``` json
"marks": {
   "properties": {
       "enter": {
          "width": { "band": false, "value": 60}
}}}
```

![image](https://cloud.githubusercontent.com/assets/1218/7950600/561ab93e-096b-11e5-9e1a-6bf362a4a791.png)

Bars no longer centered on ticks
### Width and Offset

``` json
"marks": {
   "properties": {
       "enter": {
          "width": { "band": false, "value": 60, "offset": 30}
}}}
```

![vega_live_editor](https://cloud.githubusercontent.com/assets/1218/7950271/36a19fb4-0966-11e5-9254-aed23c4d2de9.png)

Offset only adding padding to the right-hand side, not "shifting" the entire bar to the right.
## Histograms

Using Polestar to create a binned histogram: 

![image](https://cloud.githubusercontent.com/assets/1218/7950582/ffc87d1e-096a-11e5-9ab3-387ce0d0569e.png)

The ranges should have the starting value on the left-side of the bar, and the end value on the right-side. 

thoughts @kanitw @arvind

**Comment by marcprux** [comment]
This has been an open issue for a couple of years in Vega 1: https://github.com/trifacta/vega/issues/64

**Comment by arvind** [comment]
So a couple of things here. @kanitw and I figured out that if you set the [`padding` property](https://github.com/uwdata/vega/wiki/Scales#ordinal-scale-properties) of the `x` scale to `0.5`, that should get you the scenario you're looking for @ajturner. 

With regards to an x/y center, I could be wrong (@jheer?) but 4d6cc14 added [`xc` and `yc` properties](https://github.com/trifacta/vega/commit/4d6cc1492c80ba0b9f93f67501c6d6b4d5a696c4#diff-439d224289f3d86f42244ac98d50835dR4478), though we failed to document their inclusion. We'll resolve this with the v2 documentation. 

There's probably some work we can do with the extent properties (`x, x2, xc, width` and `y, y2, yc, height`) to make such positioning tasks easier. Any ideas?

**Comment by marcprux** [comment]
FTR, I couldn't get the "xc" property to do anything different than "x" with "rect" marks. However, the scale "padding" does help solve this problem:

``` json
{
  "width": 500,
  "height": 200,
  "padding": "strict",
  "data": [
    {
      "name": "table",
      "values": [
        {"x": "Category 1",  "y": 11}, {"x": "Category 2",  "y": 22},
        {"x": "Category 3",  "y": 44}, {"x": "Category 4",  "y": 88}
      ]
    }
  ],
  "scales": [
    {
      "name": "xs",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table", "field": "x"},
      "padding": 0.5
    },
    {
      "name": "ys",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "xs"},
    {"type": "y", "scale": "ys"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "x": {"scale": "xs", "field": "x"},
          "width": {"scale": "xs", "band": true},
          "y": {"scale": "ys", "field": "y"},
          "y2": {"scale": "ys", "value": 0},
          "fill": {"value": "steelblue"}
        }
      }
    }
  ]
}
```
