### ISSUE TITLE
Faceted datasets, when sourced do not inherit children

### ISSUE THREAD

**Issue by meetamit** [uwdata/vega#67]
Given a faceted dataset A and another dataset B whose `source` is A:

Since the resulting groups in B do not inherit their `_id` from A, the GroupBuilder attempts to [associate B's groups](https://github.com/uwdata/vega/blob/v2/src/scene/GroupBuilder.js#L207) with non-existent datasets named vg__bb_ instead of vg__aa_.

This is demonstrated by the spec below, which draws two trendlines by faceting `flat_data` into `grouped_data` then sourcing it as `sourced_group_data`. Rendering the marks with `"from": { "data": "grouped_data" }` works as expected, but `"from": { "data": "sourced_grouped_data" }`, as shown, breaks it.

```
{
  "width": 400,
  "height": 400,
  "padding": { "top": 0, "left": 0, "right": 0, "bottom": 0 },

  "data": [
    {
      "name": "flat_data",
      "values": [
        { "category": "A", "x": 0,   "y": 300 },
        { "category": "A", "x": 100, "y": 400 },
        { "category": "A", "x": 200, "y": 300 },
        { "category": "A", "x": 300, "y": 100 },
        { "category": "A", "x": 400, "y": 200 },
        { "category": "B", "x": 0,   "y": 200 },
        { "category": "B", "x": 100, "y": 100 },
        { "category": "B", "x": 200, "y": 400 },
        { "category": "B", "x": 300, "y": 300 },
        { "category": "B", "x": 400, "y": 400 }
      ]
    },
    {
      "name": "grouped_data",
      "source": "flat_data",
      "transform": [
        {
          "type": "facet",
          "groupby": "category"
        }
      ]
    },
    {
      "name": "sourced_grouped_data",
      "source": "grouped_data"
    }
  ],

  "marks": [
    {
      "type": "group",
      "from": { "data": "sourced_grouped_data" },
      "marks": [
        {
          "type": "line",
          "properties": {
            "enter": {
              "x": { "field": "x" },
              "y": { "field": "y" },
              "stroke": { "value": "black" },
              "strokeWidth": { "value": 3 }
            }
          }
        }
      ]
    }
  ]
}
```

A quick fix for this is to change [line 207](https://github.com/uwdata/vega/blob/v2/src/scene/GroupBuilder.js#L207) to

```
inherit = "vg_"+(Object.getPrototypeOf(group.datum)._id || group.datum._id);
```

i.e, checking for the _id that `group.datum` _would have_ inherited from `__proto__`. This fix passed all tests.

Not sure where to go from here. Happy to contrib, but would need some more info, like:
Is the issue more complex than what's addressed here?
Should a proper fix iterate over the prototype chain instead of assuming a single level?
Is it necessary to use a polyfill for accessing the `__proto__` object?

Thanks!
Amit

**Comment by arvind** [comment]
This is great catch, Amit! Setting aside polyfill, there are a couple of issues I can see with us sticking with using tuple IDs to map to the faceted datasets: deriving a C data set from B, and faceting the derived C data set itself. In either case, the logic for determining the faceted datasource's name would require iterating up the prototype chain and/or verifying the datasource exists to know when to stop. 

Instead, I would propose introducing a `_facetID` field on tuples. The `Facet` operator could maintain a counter (much like we do with tuples). On every new facet, the counter would be incremented, the new datasource would be named `vg_{facetID}` and this would be stored in the corresponding tuple's `_facetID` field. With this strategy, I believe we can just rely on JavaScript's native prototypal inheritance. Derived tuples in B and C would still have the correct `_facetIDs` from their upstream counterparts, and if C was further faceted, new `_facetIDs` would be assigned to its tuples, replacing the old ones. 

What do you think of this strategy? 

If you would like to implement the fix, I'd be happy to merge in the pull request when it's ready! If not, I can take care of it too. Just a heads up, there are a couple of places that this inheritance is hardcoded (e.g., in Scale and perhaps others, I'd recommend grepping for `vg_`). So another upshot of the `_facetID` approach is centralizing the naming of faceted datasources.

**Comment by arvind** [comment]
Thanks for filing the issue, @meetamit. I went ahead and fixed the bug in 221df8c. Let me know if you still experience any issues. Thanks!

**Comment by meetamit** [comment]
@arvind, oops — I was hoping to get to it before you and save you the work, but you beat me to it. Thank you!

**Comment by arvind** [comment]
No worries! Thanks for catching and tracing the issue. It made implementing the fix orders of magnitude easier :)
