### ISSUE TITLE
Setting explicit padding inappropriately causes Graph to skip reflows, which causes bugs

### ISSUE THREAD

**Issue by meetamit** [uwdata/vega#72]
When padding is unspecified (or set to `"auto"` or `"strict"`), [`View.prototype.autopad()`](https://github.com/uwdata/vega/blob/d73209ca1ce20e1695184c7bce5cc79aceeb6986/src/core/View.js#L178) runs all the way through, without bailing early. This is in contrast to cases when padding is explicitly specified, in which case `autopad()` [exits right away](https://github.com/uwdata/vega/blob/d73209ca1ce20e1695184c7bce5cc79aceeb6986/src/core/View.js#L179) without [calling `update()`](https://github.com/uwdata/vega/blob/d73209ca1ce20e1695184c7bce5cc79aceeb6986/src/core/View.js#L203). In other words, when explicit padding is present `View.prototype.update()` gets called one time **less** than with it does when auto padding is present.

I don't think this in itself is a problem, but it indirectly causes (or exposes) problems that occur in the subsequent update that is triggered by a pulse. The easiest way to experience this bug is to add explicit padding (e.g. `padding: { top: 20, right: 20, bottom: 20, left: 20 }`) to `shiftclick_select.json` then click to select any symbol in the scatterplot. As you'll see, the very first click on a symbol fails to cause the selected symbol to be colored (however, internally, that symbol _does_ get added to `"selectedPts"`, it just doesn't get rendered in its new state). Things start behaving normally upon any subsequent click on any **other** symbol, after which there are no longer problems. We've experienced the same problem in other update-dependent scenarios — not just ones that involve adding data to a dataset (selectedPts in this case) — and it appears that in all those cases it's just the first update that gets skipped.

The superficial fix is to always reflow, by commenting out the [line where reflow is skipped](https://github.com/uwdata/vega/blob/d73209ca1ce20e1695184c7bce5cc79aceeb6986/src/dataflow/Graph.js#L98). I wasn't able to get at the root cause of this issue, but I managed to get closer to it. Kinda hard to describe this stuff, but I hope this will help:

Inside `Graph.prototype.propagate`, logging `reflowed` and the `p.stamp` reveals that `reflowed` is `true` (and therefore the necessary propagation gets inadvertently skipped) in one crucial case during propagation triggered by the first user interaction immediately following initialization. Within that propagation while-loop, I see that at first some things get propagated properly until it gets to the marks' node. At that point, I see that `n.last()` and `p.stamp` are equal and that `p.stamp` is "unexpectedly low" (i.e. `p.stamp` for the marks equals 1, the same as it was during initialization, while the stamps of the nodes that came before it in that propagation loop are set to a bigger number, like 2 or 3). This in turn causes `reflowed` to be true, which in turn cause view re-rendering to be skipped altogether.

In contrast, when padding is `"auto"`, the same scenario (ie a user interaction immediately following initialization) shows that `p.stamp` for the marks is "expectedly high" and is identical to `p.stamp` of the nodes that came before it in the propagation loop, which makes the pulse propagate beyond those marks, finally leading to the View's `_renderNode.evaluate()` getting called and the view updates as expected.

Thanks for reading!

**Comment by arvind** [comment]
Wow, thanks for the fantastic bug report, @meetamit! I ran across this bug just yesterday, with the unequal stamps being the key. I've fixed the bug in an alternate branch, which we should be merging within the next few days. In the meanwhile, you can manually apply [this one-line fix](https://github.com/uwdata/vega/commit/346e76ca0cf60090101bb93bc8cd66ec3e4f1664#diff-83f8554f8b8463b3b0945a5bc927d14dL123). This seems to have addressed the issue with padding on the `shiftclick_select` example. Let me know if you still experience errors with your other specs.

**Comment by meetamit** [comment]
Awesome, thank you @arvind! That does fix the issues we've seen that depended on the padding settings. We do have another updating issue that's independent of this one, but I haven't yet isolated or characterized it. Currently my theory is that it's caused by the Zip transform (maybe happens with other transforms as well) when the `with` data changes without there's being a change to the data to which Zip is applied. It appears that in those cases, since `input.mod` is empty and is unaffected by the mods of the `with` data, the view doesn't get updated.

I'm not sure if I've got this right, so I need to spend more time on it; also maybe I should check out the `dirtyChecking` branch and see if the behavior is different there. I can report more afterwards. But does any of this ring a bell?

**Comment by arvind** [comment]
Interesting. Do you mind opening another issue so I remember to track that down? From the sounds of it, I agree that it would appear to be an independent issue. I would avoid `dirtyChecking` for now because we're working quite low-level with the renderers, and things aren't working perfectly yet.

**Comment by meetamit** [comment]
K, will do as soon as I can formulate a simple example spec that demonstrates the issue. I will stay out of `dirtyChecking` :)

**Comment by arvind** [comment]
Thanks very much, @meetamit! Your bug reports have been super helpful at tracking down particularly insidious issues.
