### ISSUE TITLE
Ability to bind drag interactions to window.

### ISSUE THREAD

**Issue by jheer** [uwdata/vega#73]
A number of the mouse-drag interactions in the v2 examples utilize mousemove/mouseup within the target SVG/Canvas element. However, for brushing, panning and other operations it is more natural and customary for drag event processing to continue as the mouse cursor moves outside the element (or even outside the browser). Normally this is achieved by binding mousemove and mouseup events to the window object. Is there a way to specify this using Vega's event selection syntax?

**Comment by arvind** [comment]
Indeed, if no element selector is specified, Vega registers the event handlers on the canvas/svg element. Element selectors then break down for "internal" elements and "external" elements. Internal elements can be selected as either `marktype:event` (e.g., `rect:mousedown`) or as `@markName:event` (e.g., `@points:mousedown`). Any pattern that doesn't match these is then treated as an "external" element selector, which encompasses normal/full CSS selector syntax, with event handlers registered on the corresponding external elements. For example, `body:mousedown` or `.button:click`, etc.

**Comment by jheer** [comment]
Great, we should update our examples to behave accordingly then!
