### ISSUE TITLE
Transformation pipeline on faceted values appears to be disabled

### ISSUE THREAD

**Issue by dechov** [uwdata/vega#74]
From https://github.com/uwdata/vega/wiki/Upgrading-to-2.0:

> A new transform property allows you to specify a pipeline of transformations to be applied to the values within each facet.

However, the property has no effect due to [an escape clause at the time of parsing](https://github.com/uwdata/vega/blob/416a0d73bfba178838e0e045fee72778c483748b/src/parse/transforms.js#L13). Eliminating this line makes it work seemingly as expected— is there a reason for this functionality to be unavailable?

Thanks,
Paul

**Comment by arvind** [comment]
Thanks @dechov. I think that was an erroneous skip left in from an earlier formulation of the facet transform. It's been removed in 254df39.
