### ISSUE TITLE
Inconsistent API between property encoders and aggregate.

### ISSUE THREAD

**Issue by jheer** [uwdata/vega#75]
Throughout Vega we use `field` to indicate accessors to a data field. In the new aggregate syntax we instead use `name` (which is what datalib uses). We should either (a) update Vega's aggregate transforms to use `field` (mapping to datalib's `name`) or update datalib to use `field` directly. I'm guessing the latter option will be preferred (more streamlined...), but it will cause a breaking API change to datalib. Thoughts?

**Comment by arvind** [comment]
I'd prefer making the change to datalib because it would be more streamlined. However, Vega _does_ intercept the input syntax before sending it to datalib, to parse for signals. So, augmenting this to map the syntax is not inconceivable.
