### ISSUE TITLE
Changes resulting from zip transform don't propage to dependent marks when just the "with" data changes

### ISSUE THREAD

**Issue by meetamit** [uwdata/vega#76]
Given dataset A being zipped with dataset B. When B changes (but not A), the new data in B **does** get re-zipped onto A as expected, but marks that are dependent on A do not get reevaluated. This appears to be due to `input.mod` being empty, since `grouped_data` (A) hasn't changed. A Cross transform is also susceptible to this, because crossing, like zipping, also involves a B data source.

This issue can be worked around in some cases. The included spec demonstrates the correct, expected behavior by employing a workaround. Removing the workaround from this spec illustrates the problem (as explained in a bit). Since demonstrating this issue requires causing B to change as a reaction to user input, the spec gets somewhat complex. I did my best to distill it down to essentials. As a result, it might appear somewhat contrived, but we've run into this issue in multiple practical contexts.

The following spec facets `flat_data` into `grouped_data` and renders each group as a trendline. Mousing over the chart renders two circles (named `nubs`) for the two data points nearest to the mouse. This is achieved by capturing a signal `roundedMouseX`, filtering `flat_data` to find the two points whose `x` equals `roundedMouseX` and storing them as `nearest_data` (this process is a deliberate simplification of a more elaborate processing that can find the nearest points without assuming that the points are spaced exactly 100 units apart). Finally, a zip transform is used to zip `nearest_data` (a.k.a B) onto `grouped_data` (a.k.a A) as `current`. The expectation is that the changes to `nearest_data` (B) resulting from mousemove will cause the marks to re-render — even though `grouped_data` (A) is not changed.

This only works here thanks to the workaround, which artificially creates a dependency of `nubs` on the signal `roundedMouseX` by using that signal in a dummy way: `"opacity": { "signal": "roundedMouseX", "offset": 1 }`. Removing that property from the spec breaks the expected behavior. Note that in absence of this workaround, `grouped_data` still gets re-zipped as expected when `nearest_data` changes; it's just that the marks don't see this change. Again, this appears to be due to `input.mod` being empty, since `grouped_data` (A) indeed hasn't changed. The workaround employed here does not help in other cases, like when another data, C sources A and applies its own transforms. In that case, C's transforms do not reevaluate when the mouse moves for the same reasons the marks don't.

The spec:

```
{
  "width": 500,
  "height": 500,
  "padding": 20,
  "data": [
    {
      "name": "flat_data",
      "values": [
        { "category": "A", "x": 0,   "y": 300, "color": "red" },
        { "category": "A", "x": 100, "y": 400, "color": "red" },
        { "category": "A", "x": 200, "y": 300, "color": "red" },
        { "category": "A", "x": 300, "y": 100, "color": "red" },
        { "category": "A", "x": 400, "y": 200, "color": "red" },
        { "category": "B", "x": 0,   "y": 200, "color": "black" },
        { "category": "B", "x": 100, "y": 100, "color": "black" },
        { "category": "B", "x": 200, "y": 400, "color": "black" },
        { "category": "B", "x": 300, "y": 300, "color": "black" },
        { "category": "B", "x": 400, "y": 400, "color": "black" }
      ]
    },
    {
      "name": "nearest_data",
      "source": "flat_data",
      "transform": [
        {
          "type": "filter",
          "test": "datum.x == roundedMouseX"
        }
      ]
    },
    {
      "name": "grouped_data",
      "source": "flat_data",
      "transform": [
        {
          "type": "facet",
          "groupby": "category"
        },
        {
          "type": "zip",
          "with": "nearest_data",
          "as": "current",
          "key": "category",
          "withKey": "category"
        }
      ]
    }
  ],
  "signals": [
    {
      "name": "roundedMouseX",
      "init": 0,
      "streams": [
        {
          "type": "mousemove",
          "expr": "max(0, min(400, round(event.vgX / 100) * 100))"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "trendlines",
      "type": "group",
      "from": {
        "data": "grouped_data"
      },
      "marks": [
        {
          "type": "line",
          "properties": {
            "enter": {
              "x": { "field": "x" },
              "y": { "field": "y" },
              "stroke": { "field": "color" },
              "strokeWidth": { "value": 3 }
            }
          }
        }
      ]
    },
    {
      "name": "nubs",
      "type": "symbol",
      "from": {
        "data": "grouped_data"
      },
      "properties": {
        "update": {
          "fill": { "field": "current.color" },
          "x": { "field": "current.x" },
          "y": { "field": "current.y" },
          "opacity": { "signal": "roundedMouseX", "offset": 1 }
        }
      }
    }
  ]
}
```

So... within `Zip.prototype.transform()` Is there a simple way to flag the fact that A is changed — even if just B changes — so that the propagation continues past the data?

Thanks for reading!

**Comment by arvind** [comment]
Hi @meetamit, thanks for another great bug report. This particular bug was due to the fact that the Aggregate and Facet transforms were only propagating `input.mod` tuples if they had been explicitly modified upstream. With this particular spec, tuples were in `input.mod` due to a `reflow` such that they could be re-zipped downstream. This bug should be fixed in a448f66. 

Did the similar issues you experienced with Cross also involve an Aggregate/Facet? If not, do you mind re-opening the issue with another spec that demonstrates the error? Thanks!

**Comment by meetamit** [comment]
Awesome. Thanks @arvind! (And sorry about the delay getting back to this.) The latest v2 fixes all the updating issues I've encountered.

Regarding the Cross transform: I should have made it clear that I didn't actually try it out with a cross transform — I just figured that it would behave the same as Zip, because my characterization of the issue assumed it stemmed from the dependency on a 2nd dataset. Hopefully that didn't cause any wasted effort for you...

BTW, when updating to the latest version, I did get tripped up for a little bit: was getting some unexpected runtime errors until I realized dashes (`-`) in mark names, or the referencing of those names (via `@`), isn't supported anymore.

Thanks again,
Amit

**Comment by arvind** [comment]
Glad your issues have been resolved :) 

Hmm, dashes shouldn't be illegal. I'll track that down. And where were you referencing the names via `@`? That should still work (at least with signals) e.g., the scatterplot brushing+linking example.

**Comment by meetamit** [comment]
Ok, then I'll track it down and report back (in a new issue) once I do.
