### ISSUE TITLE
panzoom demo stutters when trying to zoom

### ISSUE THREAD

**Issue by JobLeonard** [uwdata/vega#91]
Exactly like the title says: it zooms for a moment, then stops. Panning still works fine though. I made a little screencapture to show the effect:

https://youtu.be/UlrHnesO2nA

As you can see the demo used to work just fine in Vega 2.x. 

Tested in both Chrome and Firefox, with both trackpad and USB mouse, on an Ubuntu 16.04 distro.

**Comment by jheer** [comment]
Thanks! The culprit appears to be missing `"force": true` directives that ensure that `wheel` events are processed regardless if the `zoom` signal value changes or not. I pushed a fix in b7c0dfa9c3e11b2d1642e59f78b4812ac04b34cd.

I was able to replicate the error and verify a solution using Chrome within a Windows 10 virtual machine. If the fix does not work for you, please feel free to re-open the issue.

**Comment by JobLeonard** [comment]
Yep, it works here as well! ~~Just a heads-up: I got this (seemingly unrelated) test error after running `git pull`, `npm install`~~

```
 not ok 13 ValidationError: Data does not match any schemas from "oneOf"
  ---
    operator: ok
    expected: true
    actual:   false
    at: Test.<anonymous> (/home/job/Dev/LinnarssonLab/vega/test/schema-test.js:67:9)
  ...
```

EDIT: running a clean install fixed this, must have been some weird NPM caching issue on my side.

**Comment by jheer** [comment]
Yes, a bunch of modules are still being updated, so periodically flushing the node_modules can help (unless you have local `npm link` connections between repos). I just pushed a significant update that also affects the Vega 3 JSON syntax, so you will want to do this again now.
