### ISSUE TITLE
[Request] A "learn X in Y minutes"-style spec of Vega

### ISSUE THREAD

**Issue by JobLeonard** [uwdata/vega#92]
Just a thought; this could be a great introduction to Vega 3.0 once it lands:
https://learnxinyminutes.com/

I know the JSON spec doesn't allow comments, so this might be hard to do as a pure spec. Then again, they managed to make a decent JSON X in Y minutes document too:

https://learnxinyminutes.com/docs/json/

**Comment by jheer** [comment]
Thanks for the suggestion. Closing here as Vega 3 development has now migrated to the [vega/vega](https://github.com/vega/vega) repo.

**Comment by JobLeonard** [comment]
Should I re-open it over there?
