### ISSUE TITLE
rename axes `count` to `tickCount` ?

### ISSUE THREAD

**Issue by g3o2** [uwdata/vega#93]
Wouldn't it be more intuitive to rename the `count` property to `tickCount`, the latter naming convention going hand in hand with the other tick related properties such as `tickSize` ?

It appears the name change from `ticks` to `count` may have its source in the D3 function [`axis.ticks([count[, specifier]])`](https://github.com/d3/d3-axis/blob/master/README.md#axis_ticks).

``` javascript
"axes": [
  {"orient": "bottom", "scale": "x", "count": 6}
]
```

vs

``` javascript
"axes": [
  {"orient": "bottom", "scale": "x", "tickCount": 6}
]
```

**Comment by jheer** [comment]
Thanks for the suggestion! I agree that the current name is ambiguous. The name `count` arises from that same argument name being used as part of D3 v4. There is also another consistency concern, as we have an analogous `count` parameter that can be used for configuring discrete legends over continuous domains. Do you think it is sensible to use `tickCount` there as well, even though those aren't technically "ticks"?

**Comment by g3o2** [comment]
Thank you for considering the suggestion!
Though I wonder what would speak against maintaining the old name `ticks` ? In a way, there has not been any name change from v3 to v4 in D3, so it is a bit surprising to see Vega 2's `ticks` being replaced by `count`or `tickCount` in Vega 3.

Regarding the other consistency concern, my understanding is that using `ticks` (or `tickCount`) in the described context would be consistent with D3 jargon. That's because `ticks` are de facto a property of [`d3-scale`](https://github.com/d3/d3-scale#continuous_ticks) and therefore technically never (just) "ticks".

P.S.: Mr Heer, let me also express my congratulations! (cf. google discussion)

**Comment by jheer** [comment]
I've renamed `count` to `tickCount`. This resulted in changes to vega-parser and updates to the example specs in this repo. While there is a reasonable argument to be made for sticking with `ticks` (as in Vega 2), this also could be confused with `values` (which gives explicit tick values). Given the change, I think `tickCount` is the least ambiguous option. This change affects both axis and legend definitions.
