### ISSUE TITLE
Alternative for animated transitions?

### ISSUE THREAD

**Issue by ronakrrb** [uwdata/vega#94]
The version 3 porting guide states that animated transitions are not supported. What would be the reason for not supporting and removing delay and ease? Any alternatives for this?

**Comment by marcprux** [comment]
I was also startled by that note in the porting guide. Does the statement that animated transitions are "not currently supported" in vega 3.0 mean that they will eventually be supported? I.e., is this just a limitation of the beta? We use animated transitions extensively in our projects, so we won't be able to migrate to a version that doesn't support them.

**Comment by jheer** [comment]
We do not plan to include animated transitions in the initial 3.0 release, but they are a likely candidate for a subsequent release (e.g., 3.1) -- but we will prioritize this in part based on the community response! Our top priority is ensuring full support for Vega-Lite 2.0, and our sense so far is that animated transitions are only sparingly used (if at all) by most Vega users.

One alternative (for SVG rendering only) is to use CSS animation instead, which will almost certainly be more efficient. We do not have ready-made examples for this (yet) using Vega 3 proper, but do have related examples using lower-level Vega dataflows in the [vega-dataflow-examples repo](https://github.com/vega/vega-dataflow-examples). I will update this issue once a dedicated Vega 3 + CSS animation example is ready to share.

**Comment by jheer** [comment]
Notes/TODOs on how we might implement animated transitions in Vega 3:
- [ ] Design Vega 3 animation syntax (allow per-item `duration`/`ease`/`delay` within encode sets?)
- [ ] Add interpolation and scheduling support to vega-scenegraph
- [ ] Update Scale transform in vega-encode to persist previous scales
- [ ] Update vega-parser to allow access to previous scales
- [ ] Update Encoder in vega-encode to snapshot scenegraph item values prior to animation
- [ ] Update vega-view to orchestrate animation and retain animated exiting items (as needed)

**Comment by jheer** [comment]
Closing here. Issue has been migrated to vega/vega#641.
