### ISSUE TITLE
Enable targeted error output

### ISSUE THREAD

**Issue by jheer** [uwdata/vega#96]
It would be valuable to target error messages to receivers other than just the JavaScript console. As discussed earlier by @jakevdp, @kanitw and others, this issue notably arises for Altair users in Python.

Vega Dataflow (and hence also Vega View) allows both logging and error handling methods to be over-ridden, providing a straightforward mechanism for doing this. For example, the Vega View class could update output HTML with error messages to make it visible in the browser. However, that might not always be desirable and so would need to be configurable. (Note that in Vega 3, parsing from JSON to Dataflow is a completely separate step, with a different error-handling surface area. So parse errors and runtime errors are separate categories to handle!)

Also, might it be feasible to route error messages back to Python (or other external language environments)? Perhaps that is something ipyvega might do? Thoughts / input welcome.

**Comment by jakevdp** [comment]
Routing errors back to Python would be nice. I'm not particularly familiar with the JS/Python communication protocol, but @ellisonbg would probably be able to comment on that.

**Comment by kanitw** [comment]
Would love to know how JS-Python communication works too.  
I just added custom logger support to Vega-Lite in our 2.0 development :)

**Comment by jheer** [comment]
Migrated issue to vega/vega#640. Closing here.
